### ISSUE TITLE
[Responsive] Flash of content when using multiple Responsive components and server-side rendering

### ISSUE THREAD

**Issue by ryanoglesby08** [telusdigital/tds#461]
## Description

I want to render one component when a media query matches, and another component when another query matches. When I accomplish this using multiple `Responsive` components along with server side rendering, I see both components briefly.

Here is an example:

```jsx
<div>
  <Responsive maxWidth="md" render={() => (
    <Text>Render me below medium breakpoint.</Text>
  )}/>

  <Responsive minWidth="md" render={() => (
    <Text>Render me above medium breakpoint.</Text>
  )}/>
</div>
```
If I use SSR and then view this on a desktop, you will briefly see both the text "Render me below medium breakpoint." and "Render me above medium breakpoint."

This seems to be a bad user experience, as I should only view the of them at a time since the media queries are not overlapping.

## Reproduction Steps

- Use multiple `Responsive` components
- Use SSR
- Observe flash of content

## Meta

- TDS version: v1.0.0

**Comment by lzcabrera** [comment]
Thanks for submitting the issue @ryanoglesby08.

The Responsive component is a thin wrapper around the [react-media](https://github.com/ReactTraining/react-media/) which has a `defaultMatches` prop that can help prevent the rendering of both components on SSR:

```
<div>
  <Responsive maxWidth="md" render={() => (
    <Text>Render me below medium breakpoint.</Text>
  )}/>

  <Responsive defaultMatches minWidth="md" render={() => (
    <Text>Render me above medium breakpoint.</Text>
  )}/>
</div>
```

We are in the process of submitting a PR to [react-media](https://github.com/ReactTraining/react-media/) to document the `defaultMatches` prop on their docs.

We will keep this issue opened until we have proper documentation on the `defaultMatches` prop to point to.

**Comment by lzcabrera** [comment]
We added the "defaultMatches prop for server-side rendering" here: https://tds.telus.com/#responsive to give you an idea on what you need to do on your app to prevent the flash of content.

**Comment by theetrain** [comment]
@kretzm @Jeffrey-Chang @fzero does Laura's comment above help with your use cases? By using `defaultMatches`, you can choose to render mobile components by default.

**Comment by kretzm** [comment]
@theetrain we're not using the `<Responsive>` component in our code, but it's the TDS components that use it in their code that gives us the issue. Specifically;
- `<DisplayHeading>` [Code line](https://github.com/telusdigital/tds/blob/master/src/components/Typography/DisplayHeading/DisplayHeading.jsx#L22)

Should we look at setting `defaultMatches` to always be false for any TDS component using `<Responsive>` inside of it?

**Comment by ryanoglesby08** [comment]
@kretzm, great points. We are leaning that way too for the existing TDS components.

We will be taking on the work to make sure that TDS components render in their "mobile" view when there is no environment for running a media query (such as on a server).

Here is our JIRA defect for reference: https://telusdigital.atlassian.net/browse/TDS-517

**Comment by theetrain** [comment]
## Background and research

Though it is possible for TDS components to have `defaultMatches` set appropriately to render mobile variations first for server side rendering, there are **other caveats**:

- applications rendering for desktop users will still have a flash of content
- projects will need at least least two builds of their site in order to serve mobile and desktop sites, and be able to detect the user agent in order to deliver the best-matching site. This is not a straightforward development and would need to be replicated in every project

Since TDS components use CSS Modules, **page rendering flow** goes like this:

1. JS bundles are downloaded and executed
2. pre-rendered components are displayed and their styles are injected into multiple `<style>` tags
3. css styles are applied, showing mobile styles
4. React components get mounted, and anywhere the Responsive component is used gets called to detect the viewport width and act accordingly (this is the **flash of content**); and in some cases such as @kretzm's example above, the Responsive component doesn't get invoked and the pre-rendered styles do not change

## Proposal

- We can restore our SCSS media query mixins and refactor every TDS component to use traditional CSS media queries, but **only for styles**
- The Responsive component can be repurposed for only responsive content such as copy, prop usage, or other JS logic

The upside is there will be no flash of content for most content such as typography components or buttons. However, anytime the Responsive component is used there may always be a flash of content depending on how it is used.

Let's keep this discussion going for a bit more to gather more thoughts.

**Comment by githubjosh** [comment]
Dynamic serving and SEO considerations

https://developers.google.com/search/mobile-sites/mobile-seo/dynamic-serving

**Comment by ryanoglesby08** [comment]
@githubjosh 

Thanks for that link! 

I replied with a larger comment on the other Issue. #465 

Yeah, user agent detection can be error prone. Though if using well used libraries and not serving wildly different content, does that mitigate some of the potential pitfalls? I'm struggling a bit here, but do think that the benefits are pretty substantial and wondering if we can deal with the seo considerations fairly easily.

**Comment by theetrain** [comment]
Patched in this release: https://github.com/telusdigital/tds/releases/tag/%40tds%2Fcore-responsive%401.1.0
