### ISSUE TITLE
Open up the Isomorphic Starter Kit

### ISSUE THREAD

**Issue by jczerwinski** [telusdigital/tds#500]
The [Isomorphic Starter Kit repo](https://github.com/telusdigital/telus-isomorphic-starter-kit) is referenced [here](https://github.com/telusdigital/tds/blob/8d9f4472b5cdd99fa62549f1d68d268cc9df4c25/guide/getting-started/developers.md#installing), but is not available. As a TELUS employee, I'd like to be able to use it for internal projects.

**Comment by ryanoglesby08** [comment]
Hi @jczerwinski.

The isomorphic starter kit repo is in the telusdigital Github organization, so you will need to be a member of that org in order to see it. The TDS team does not grant access to that organization. Here is a Google form that should get you started: https://docs.google.com/forms/d/e/1FAIpQLSe7NFDt23L7xxQkQiMrF2Ksn64S6rreHUzo84anFEtD8vH45A/viewform.

If that doesn't work, you can work with your manager and People Support to get the appropriate access.

Also, small point, all public-facing TDS docs are here: https://tds.telus.com. (The master branch is currently not correct, as we are working from master on the next release.)

I'm going to go ahead and close this. Let us know if you are still having troubles and we'll try to get you pointed in the right direction.
